name: 'Typescript compiler'
description: 'Compile your Typescript code and check for errors.'
author: 'Friendly0Fire'
branding:
  icon: alert-circle
  color: blue
inputs:
  project:
    description: 'Optional project path.'
    required: false
  build:
    description: 'Optional tsconfig.json path; enables build mode.'
    required: false
  executable:
    description: 'Compilation Executable (e.g. tsc or ttsc)'
    default: 'tsc'
    required: false
runs:
  using: 'node12'
  main: 'dist/main.js'
